# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b50868d76422f0bc7f1504366b52eb5b4471e29e56b7771f3cda7f1064efced7b000ea7af52c1d676d2cddbdfa463b96595959aa9068d85a916322413740996

test:
  secret_key_base: 7bf184fe0e88c7053402293a9b9ff6446ac1145aef81322c3cb951a5a4ea4e2710007e38b73d0b0e1dcb7e01b6b5e23957b94dca12b041e357129423ddf7389a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
